[package]
name = "gxhashtest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "1.6", features = ["v4"] }
gxhash = "2.3.0"
rand = "0.8.5"
rand_chacha = "0.3.1"